CREATE DATABASE event_thunder_users;
CREATE DATABASE event_thunder_events;
CREATE DATABASE event_thunder_subscribe;
CREATE DATABASE event_thunder_ticketing;
CREATE DATABASE event_thunder_comments;
CREATE DATABASE event_thunder_posts;